palette = "catppuccin_mocha"

format = """
[󰍞](fg:text)\
$shell\
[󰇙](fg:text)\
$username\
[󰇙](fg:text)\
$directory\
[󰇙](fg:text)\
$git_branch\
$git_commit\
$git_metrics\
$git_status\
[󰇙](fg:text)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$python\
[󰇙](fg:text)\
$docker_context\
$Container\
[󰇙](fg:text)\
$time\
[󰍟](fg:text)
$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[shell]
disabled = false
bash_indicator = ''
zsh_indicator = '󰬡'
powershell_indicator = '󰨊'
unknown_indicator = ''
style = "fg:flamingo"
format = '[ $indicator ]($style)'

[username]
show_always = true
style_user = "fg:pink"
style_root = "fg:pink"
format = '[ $user ]($style)'

[directory]
format = "[ $path ]($style)"
truncation_length = 100
truncation_symbol = "…/"
truncate_to_repo = false
style = "fg:maroon"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"OneDrive - 独立行政法人 国立高等専門学校機構" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "󰈙"
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "fg:yellow"
format = '[ $symbol $branch ]($style)'

[git_status]
windows_starship = '/mnt/c/Program Files/starship/bin/starship.exe'
style = "fg:yellow"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
style = "fg:teal"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "fg:teal"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:teal"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "fg:teal"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:teal"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:teal"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:teal"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:teal"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:teal"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:teal"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:teal"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "fg:teal"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:sapphire"
format = '[ $symbol $context ]($style) $path'

[container]
style = "fg:sapphire"
format = '[$symbol \[$name\]]($style)'

[time]
disabled = false
style = "fg:lavender"
time_format = "%R" # Hour:Minute Format
format = '[  $time ]($style)'

[character]
error_symbol = "[](bold red)"
success_symbol = "[](bold green)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
